### PR TITLE
Copy emails

### PR DESCRIPTION
**Pull request by daniel-henderson1**

### CODE REVIEW

**Comment by lizcooper44** [comment]
Awesome! Excited that we were able to actually do this. Is there any way to make it so you can select multiple teams if you want to and copy the emails? Also, can we change the button to 'copy student emails' since it doesn't include the client email? The use case here was WP wanting to select all the students in her sections and copy their emails. Being nitpicky, but it would be cool if the success message automatically faded out instead of having to click out of it (not high priority though if this is too difficult)

**Comment by daniel-henderson1** [comment]
> Awesome! Excited that we were able to actually do this. Is there any way to make it so you can select multiple teams if you want to and copy the emails? Also, can we change the button to 'copy student emails' since it doesn't include the client email? The use case here was WP wanting to select all the students in her sections and copy their emails. Being nitpicky, but it would be cool if the success message automatically faded out instead of having to click out of it (not high priority though if this is too difficult)

Was able to make all of those changes.

**Review by dosorno7 — APPROVED** [review]
Ran through some manual testing and appears to be working just as needed.

**Review by JuanNRamirez — APPROVED** [review]
LGTM

**Pull request merged**
